version: '3'
services:
    node:
        image: node:lts-jessie
        ports:
            - 8080:8080
        volumes:
            - .:/code
        working_dir: /code
        command: sh -c 'npm install && npm run dev'
